# Generated by Django 3.0.6 on 2020-05-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
